services:
  app:
    container_name: flask-app
    tty: true
    command: bash
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../:/workspace
    depends_on:
      - db
    environment:
      - FLASK_APP=src/app.py
      - FLASK_ENV=development
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    env_file:
      - .env
    networks:
      - backend

  db:
    container_name: mysql-db
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - TZ=${DB_TIMEZONE}
    env_file:
      - .env
    ports:
        - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - backend

volumes:
  db-data:

networks:
  backend:
    driver: bridge