services:
  flask-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../src:/workspace/src
    depends_on:
      - flask-db
    command: sleep infinity
    environment:
      - FLASK_APP=src/app.py
      - FLASK_ENV=development
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    networks:
      - backend

  flask-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
        - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

volumes:
  db-data: {}

networks:
  backend:
    driver: bridge