services:
  app:
    container_name: flask-app
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../src:/workspace/src
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - backend

  db:
    container_name: mysql-db
    image: mysql:8.0
    env_file:
      - .env
    ports:
        - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:

networks:
  backend:
    driver: bridge