name: Lint Check

on:
  push:
    branches:
      - feature/ci_linter
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file from secrets
        run: |
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .devcontainer/.env
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .devcontainer/.env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .devcontainer/.env
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .devcontainer/.env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker containers
        run: make build

      - name: Run flake8 lint
        run: make lint
